version: '1'

services:
  # Hosts the stream
  icecast:
    container_name: icecast
    build:
      context: ./icecast
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8000
    networks:
      - tor-radio-network

  # Streams the audio to the icecast server
  ices:
    container_name: ices
    build:
      context: ./ices
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./music/dump:/usr/share/ices/music/dump
      - ./music/staging:/usr/share/ices/music/staging
      - ./music/ogg:/usr/share/ices/music/ogg
    depends_on:
      - icecast
    networks:
      - tor-radio-network

  # Hosts the webpage for users to play the icecast stream
  nginx-tor:
    container_name: nginx-tor
    build:
      context: ./nginx-tor
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./nginx-tor/tor/info:/var/lib/tor/icecast
    depends_on:
      - icecast
    networks:
      - tor-radio-network
    
networks:
  tor-radio-network:
    driver: bridge
